// GENERATED by tools/gen_gl_loader.py -- do not edit by hand.
//
// Real definitions for the GL entry points this engine calls directly and
// that opengl32.dll does not export. Prototypes are taken verbatim from the
// vendored Khronos headers, so these match what the sources were compiled
// against; each one forwards to a pointer resolved at init.
//
// PCVR_GL_Init() must be called once, with a current GL context, before any
// of these are used. GLimp_Init does that.

#include <windows.h>
#include <stdio.h>
#include <GLES2/gl2.h>
#include <GLES3/gl3.h>
#include "gl_loader.h"

// wglGetProcAddress only resolves entry points newer than GL 1.1, and
// returns one of several documented failure values rather than just NULL.
void *PCVR_GL_GetProc( const char *name ) {
	PROC p = wglGetProcAddress( name );

	if ( p == 0 || p == (PROC)0x1 || p == (PROC)0x2 || p == (PROC)0x3 ||
			p == (PROC)-1 ) {
		HMODULE m = GetModuleHandleA( "opengl32.dll" );
		p = m ? GetProcAddress( m, name ) : 0;
	}

	return (void *)p;
}

typedef void (GL_APIENTRY *PFN_PCVR_glBindBuffer)(GLenum target, GLuint buffer);
typedef void (GL_APIENTRY *PFN_PCVR_glBindBufferBase)(GLenum target, GLuint index, GLuint buffer);
typedef void (GL_APIENTRY *PFN_PCVR_glBindFramebuffer)(GLenum target, GLuint framebuffer);
typedef void (GL_APIENTRY *PFN_PCVR_glBindRenderbuffer)(GLenum target, GLuint renderbuffer);
typedef void (GL_APIENTRY *PFN_PCVR_glBufferData)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
typedef GLenum (GL_APIENTRY *PFN_PCVR_glCheckFramebufferStatus)(GLenum target);
typedef void (GL_APIENTRY *PFN_PCVR_glDeleteBuffers)(GLsizei n, const GLuint *buffers);
typedef void (GL_APIENTRY *PFN_PCVR_glDeleteFramebuffers)(GLsizei n, const GLuint *framebuffers);
typedef void (GL_APIENTRY *PFN_PCVR_glDeleteRenderbuffers)(GLsizei n, const GLuint *renderbuffers);
typedef void (GL_APIENTRY *PFN_PCVR_glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
typedef void (GL_APIENTRY *PFN_PCVR_glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
typedef void (GL_APIENTRY *PFN_PCVR_glGenFramebuffers)(GLsizei n, GLuint *framebuffers);
typedef void (GL_APIENTRY *PFN_PCVR_glGenRenderbuffers)(GLsizei n, GLuint *renderbuffers);
typedef GLuint (GL_APIENTRY *PFN_PCVR_glGetUniformBlockIndex)(GLuint program, const GLchar *uniformBlockName);
typedef void (GL_APIENTRY *PFN_PCVR_glInvalidateFramebuffer)(GLenum target, GLsizei numAttachments, const GLenum *attachments);
typedef void * (GL_APIENTRY *PFN_PCVR_glMapBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
typedef void (GL_APIENTRY *PFN_PCVR_glRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
typedef void (GL_APIENTRY *PFN_PCVR_glTexStorage3D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
typedef void (GL_APIENTRY *PFN_PCVR_glUniformBlockBinding)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
typedef GLboolean (GL_APIENTRY *PFN_PCVR_glUnmapBuffer)(GLenum target);

static PFN_PCVR_glBindBuffer p_glBindBuffer;
static PFN_PCVR_glBindBufferBase p_glBindBufferBase;
static PFN_PCVR_glBindFramebuffer p_glBindFramebuffer;
static PFN_PCVR_glBindRenderbuffer p_glBindRenderbuffer;
static PFN_PCVR_glBufferData p_glBufferData;
static PFN_PCVR_glCheckFramebufferStatus p_glCheckFramebufferStatus;
static PFN_PCVR_glDeleteBuffers p_glDeleteBuffers;
static PFN_PCVR_glDeleteFramebuffers p_glDeleteFramebuffers;
static PFN_PCVR_glDeleteRenderbuffers p_glDeleteRenderbuffers;
static PFN_PCVR_glFramebufferRenderbuffer p_glFramebufferRenderbuffer;
static PFN_PCVR_glFramebufferTexture2D p_glFramebufferTexture2D;
static PFN_PCVR_glGenFramebuffers p_glGenFramebuffers;
static PFN_PCVR_glGenRenderbuffers p_glGenRenderbuffers;
static PFN_PCVR_glGetUniformBlockIndex p_glGetUniformBlockIndex;
static PFN_PCVR_glInvalidateFramebuffer p_glInvalidateFramebuffer;
static PFN_PCVR_glMapBufferRange p_glMapBufferRange;
static PFN_PCVR_glRenderbufferStorage p_glRenderbufferStorage;
static PFN_PCVR_glTexStorage3D p_glTexStorage3D;
static PFN_PCVR_glUniformBlockBinding p_glUniformBlockBinding;
static PFN_PCVR_glUnmapBuffer p_glUnmapBuffer;

GL_APICALL void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer) {
	p_glBindBuffer( target, buffer );
}

GL_APICALL void GL_APIENTRY glBindBufferBase (GLenum target, GLuint index, GLuint buffer) {
	p_glBindBufferBase( target, index, buffer );
}

GL_APICALL void GL_APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer) {
	p_glBindFramebuffer( target, framebuffer );
}

GL_APICALL void GL_APIENTRY glBindRenderbuffer (GLenum target, GLuint renderbuffer) {
	p_glBindRenderbuffer( target, renderbuffer );
}

GL_APICALL void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const void *data, GLenum usage) {
	p_glBufferData( target, size, data, usage );
}

GL_APICALL GLenum GL_APIENTRY glCheckFramebufferStatus (GLenum target) {
	return p_glCheckFramebufferStatus( target );
}

GL_APICALL void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint *buffers) {
	p_glDeleteBuffers( n, buffers );
}

GL_APICALL void GL_APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint *framebuffers) {
	p_glDeleteFramebuffers( n, framebuffers );
}

GL_APICALL void GL_APIENTRY glDeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers) {
	p_glDeleteRenderbuffers( n, renderbuffers );
}

GL_APICALL void GL_APIENTRY glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
	p_glFramebufferRenderbuffer( target, attachment, renderbuffertarget, renderbuffer );
}

GL_APICALL void GL_APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
	p_glFramebufferTexture2D( target, attachment, textarget, texture, level );
}

GL_APICALL void GL_APIENTRY glGenFramebuffers (GLsizei n, GLuint *framebuffers) {
	p_glGenFramebuffers( n, framebuffers );
}

GL_APICALL void GL_APIENTRY glGenRenderbuffers (GLsizei n, GLuint *renderbuffers) {
	p_glGenRenderbuffers( n, renderbuffers );
}

GL_APICALL GLuint GL_APIENTRY glGetUniformBlockIndex (GLuint program, const GLchar *uniformBlockName) {
	return p_glGetUniformBlockIndex( program, uniformBlockName );
}

GL_APICALL void GL_APIENTRY glInvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments) {
	p_glInvalidateFramebuffer( target, numAttachments, attachments );
}

GL_APICALL void * GL_APIENTRY glMapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access) {
	return p_glMapBufferRange( target, offset, length, access );
}

GL_APICALL void GL_APIENTRY glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height) {
	p_glRenderbufferStorage( target, internalformat, width, height );
}

GL_APICALL void GL_APIENTRY glTexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth) {
	p_glTexStorage3D( target, levels, internalformat, width, height, depth );
}

GL_APICALL void GL_APIENTRY glUniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding) {
	p_glUniformBlockBinding( program, uniformBlockIndex, uniformBlockBinding );
}

GL_APICALL GLboolean GL_APIENTRY glUnmapBuffer (GLenum target) {
	return p_glUnmapBuffer( target );
}

bool PCVR_GL_Init( void ) {
	// Idempotent: GLimp_Init can be reached more than once, and the VR layer
	// owns the GL context here the way EGL does on Android, so the ordering
	// between the two is worth being tolerant about.
	static bool loaded = false;

	if ( loaded ) {
		return true;
	}

	// If this runs before a context is current, wglGetProcAddress returns
	// NULL for everything and the report below names all twenty. That is a
	// far better failure than a null call deep inside the renderer.
	int missing = 0;

	p_glBindBuffer = (PFN_PCVR_glBindBuffer)PCVR_GL_GetProc( "glBindBuffer" );
	if ( !p_glBindBuffer ) { printf( "PCVR_GL_Init: missing glBindBuffer\n" ); missing++; }
	p_glBindBufferBase = (PFN_PCVR_glBindBufferBase)PCVR_GL_GetProc( "glBindBufferBase" );
	if ( !p_glBindBufferBase ) { printf( "PCVR_GL_Init: missing glBindBufferBase\n" ); missing++; }
	p_glBindFramebuffer = (PFN_PCVR_glBindFramebuffer)PCVR_GL_GetProc( "glBindFramebuffer" );
	if ( !p_glBindFramebuffer ) { printf( "PCVR_GL_Init: missing glBindFramebuffer\n" ); missing++; }
	p_glBindRenderbuffer = (PFN_PCVR_glBindRenderbuffer)PCVR_GL_GetProc( "glBindRenderbuffer" );
	if ( !p_glBindRenderbuffer ) { printf( "PCVR_GL_Init: missing glBindRenderbuffer\n" ); missing++; }
	p_glBufferData = (PFN_PCVR_glBufferData)PCVR_GL_GetProc( "glBufferData" );
	if ( !p_glBufferData ) { printf( "PCVR_GL_Init: missing glBufferData\n" ); missing++; }
	p_glCheckFramebufferStatus = (PFN_PCVR_glCheckFramebufferStatus)PCVR_GL_GetProc( "glCheckFramebufferStatus" );
	if ( !p_glCheckFramebufferStatus ) { printf( "PCVR_GL_Init: missing glCheckFramebufferStatus\n" ); missing++; }
	p_glDeleteBuffers = (PFN_PCVR_glDeleteBuffers)PCVR_GL_GetProc( "glDeleteBuffers" );
	if ( !p_glDeleteBuffers ) { printf( "PCVR_GL_Init: missing glDeleteBuffers\n" ); missing++; }
	p_glDeleteFramebuffers = (PFN_PCVR_glDeleteFramebuffers)PCVR_GL_GetProc( "glDeleteFramebuffers" );
	if ( !p_glDeleteFramebuffers ) { printf( "PCVR_GL_Init: missing glDeleteFramebuffers\n" ); missing++; }
	p_glDeleteRenderbuffers = (PFN_PCVR_glDeleteRenderbuffers)PCVR_GL_GetProc( "glDeleteRenderbuffers" );
	if ( !p_glDeleteRenderbuffers ) { printf( "PCVR_GL_Init: missing glDeleteRenderbuffers\n" ); missing++; }
	p_glFramebufferRenderbuffer = (PFN_PCVR_glFramebufferRenderbuffer)PCVR_GL_GetProc( "glFramebufferRenderbuffer" );
	if ( !p_glFramebufferRenderbuffer ) { printf( "PCVR_GL_Init: missing glFramebufferRenderbuffer\n" ); missing++; }
	p_glFramebufferTexture2D = (PFN_PCVR_glFramebufferTexture2D)PCVR_GL_GetProc( "glFramebufferTexture2D" );
	if ( !p_glFramebufferTexture2D ) { printf( "PCVR_GL_Init: missing glFramebufferTexture2D\n" ); missing++; }
	p_glGenFramebuffers = (PFN_PCVR_glGenFramebuffers)PCVR_GL_GetProc( "glGenFramebuffers" );
	if ( !p_glGenFramebuffers ) { printf( "PCVR_GL_Init: missing glGenFramebuffers\n" ); missing++; }
	p_glGenRenderbuffers = (PFN_PCVR_glGenRenderbuffers)PCVR_GL_GetProc( "glGenRenderbuffers" );
	if ( !p_glGenRenderbuffers ) { printf( "PCVR_GL_Init: missing glGenRenderbuffers\n" ); missing++; }
	p_glGetUniformBlockIndex = (PFN_PCVR_glGetUniformBlockIndex)PCVR_GL_GetProc( "glGetUniformBlockIndex" );
	if ( !p_glGetUniformBlockIndex ) { printf( "PCVR_GL_Init: missing glGetUniformBlockIndex\n" ); missing++; }
	p_glInvalidateFramebuffer = (PFN_PCVR_glInvalidateFramebuffer)PCVR_GL_GetProc( "glInvalidateFramebuffer" );
	if ( !p_glInvalidateFramebuffer ) { printf( "PCVR_GL_Init: missing glInvalidateFramebuffer\n" ); missing++; }
	p_glMapBufferRange = (PFN_PCVR_glMapBufferRange)PCVR_GL_GetProc( "glMapBufferRange" );
	if ( !p_glMapBufferRange ) { printf( "PCVR_GL_Init: missing glMapBufferRange\n" ); missing++; }
	p_glRenderbufferStorage = (PFN_PCVR_glRenderbufferStorage)PCVR_GL_GetProc( "glRenderbufferStorage" );
	if ( !p_glRenderbufferStorage ) { printf( "PCVR_GL_Init: missing glRenderbufferStorage\n" ); missing++; }
	p_glTexStorage3D = (PFN_PCVR_glTexStorage3D)PCVR_GL_GetProc( "glTexStorage3D" );
	if ( !p_glTexStorage3D ) { printf( "PCVR_GL_Init: missing glTexStorage3D\n" ); missing++; }
	p_glUniformBlockBinding = (PFN_PCVR_glUniformBlockBinding)PCVR_GL_GetProc( "glUniformBlockBinding" );
	if ( !p_glUniformBlockBinding ) { printf( "PCVR_GL_Init: missing glUniformBlockBinding\n" ); missing++; }
	p_glUnmapBuffer = (PFN_PCVR_glUnmapBuffer)PCVR_GL_GetProc( "glUnmapBuffer" );
	if ( !p_glUnmapBuffer ) { printf( "PCVR_GL_Init: missing glUnmapBuffer\n" ); missing++; }

	if ( missing ) {
		printf( "PCVR_GL_Init: %d of 20 entry points unresolved\n", missing );
		return false;
	}

	loaded = true;
	return true;
}
