// GENERATED by tools/gen_gl_loader.py -- do not edit by hand.
#ifndef PCVR_GL_LOADER_H
#define PCVR_GL_LOADER_H

// The VR layer is C and calls both of these; this file is compiled as C++.
// Same wrapper their own VrCommon.h uses. (The gl* entry points below do
// not need it: the Khronos headers already declare them extern "C".)
#ifdef __cplusplus
extern "C" {
#endif

// Resolves the GL entry points opengl32.dll does not export. Call once,
// with a current GL context, before any rendering. Returns false and names
// the offenders on stdout if anything is unresolved.
bool PCVR_GL_Init( void );

// Resolves any GL entry point by name: wglGetProcAddress, falling back to
// opengl32.dll for the GL 1.1 set it refuses. This is what
// GLimp_ExtensionPointer uses on Windows to fill the engine qgl pointers.
void *PCVR_GL_GetProc( const char *name );


#ifdef __cplusplus
}
#endif

#endif
