"""Does every image the options page asks for actually exist?

A .guifragment row that names a material nothing provides does not fail: idTech4
substitutes the default and carries on, or draws nothing. Since the ten rows
added this week were generated from a template, a wrong asset path would be
wrong in all ten at once - and would look exactly like "the rows did not appear".

Checks every material named in the fragment against the retail paks, the VR pk4,
and the .mtr files that declare materials by name rather than by file.
"""
import io
import os
import re
import zipfile

REPO = 'E:/Tools/Games/PreyVR-PCVR'
PAKS = 'E:/Games/PreyVR-PCVR/preybase'
GUI = os.path.join(REPO,
                   'app/src/main/pk4/guis/mainmenu/mainmenu_options.guifragment')

RETAIL = ('pak000.pk4', 'pak001.pk4', 'pak002.pk4', 'pak003.pk4', 'pak004.pk4',
          'pak005.pk4', 'pak006.pk4', 'pak020.pk4', 'pak040.pk4',
          'vr_support.pk4')

files = set()
mtr_names = set()
for name in RETAIL:
    p = os.path.join(PAKS, name)
    if not os.path.exists(p):
        continue
    z = zipfile.ZipFile(p)
    for n in z.namelist():
        if n.endswith('/'):
            continue
        files.add(n.lower().replace('\\', '/'))
        if n.lower().endswith('.mtr'):
            t = z.read(n).decode('latin-1', 'replace')
            # a material declaration is a bare name at the start of a line
            for m in re.finditer(r'^\s*([A-Za-z0-9_/\\.\-]+)\s*$', t, re.M):
                mtr_names.add(m.group(1).lower().replace('\\', '/'))

gui = io.open(GUI, encoding='latin-1', newline='').read()

wanted = []
seen = set()
for m in re.finditer(r'(?:background|leftMat|middleMat|rightMat|thumbShader|'
                     r'liveUpdate|matcolor|shader)\s+"([^"]+)"', gui):
    v = m.group(1).strip().lower().replace('\\', '/')
    if not v or v in seen or not re.search(r'[a-z]', v):
        continue
    seen.add(v)
    wanted.append(v)


def resolve(v):
    # _black, _white, _default and friends are generated by the engine, not
    # loaded from a pak. Reporting them missing is the check being wrong.
    if v.startswith('_'):
        return 'yes (engine internal)'
    if v in files or v in mtr_names:
        return 'yes'
    for ext in ('.tga', '.dds', '.jpg', '.png'):
        if v + ext in files:
            return 'yes (%s)' % ext
        base = re.sub(r'\.(tga|dds|jpg|png)$', '', v)
        if base + ext in files:
            return 'yes (%s)' % ext
    if re.sub(r'\.(tga|dds|jpg|png)$', '', v) in mtr_names:
        return 'yes (material)'
    return 'NO'


print('%-52s %s' % ('asset named by the options page', 'present'))
print('-' * 70)
bad = []
for v in sorted(wanted):
    r = resolve(v)
    print('%-52s %s' % (v[:52], r))
    if r == 'NO':
        bad.append(v)

print()
if bad:
    print('MISSING')
    for v in bad:
        print('  ' + v)
else:
    print('every image the options page names resolves in the paks')

# control: a made-up path must not resolve
assert resolve('guis/assets/menu/there_is_no_such_thing.tga') == 'NO', \
    'the check has no power - a made-up path resolved'
print('(control: a made-up path is reported missing)')
