"""NOT USED. Kept for the measurements in it and so nobody tries this again.

This closes the open surfaces in Prey's weapon viewmodels by mirroring
triangles. It works - 8,783 open edges closed, every skeleton byte-identical -
and it is still the wrong answer, which took a headset to find out.

WHY IT DOES NOT WORK
--------------------
PreyVR's weapon models are not "retail plus back faces". They are remodelled.
Comparing the vertex WEIGHTS, which is what actually places geometry relative to
the bones, against retail:

    autocannon   2235 -> 3858    (+73%)
    launcher     1692 -> 3419   (+102%)
    soulstripper 1713 -> 3732   (+118%)
    bow          1721 ->  974    (-43%)
    wrench        918 ->  673    (-27%)

Three consequences, all of which showed up in the headset:

  the hands     retail viewmodels include the player's hands and arms, because
                a flat shooter needs them. They were removed for VR, where you
                have controllers. Going back to retail brings them back.
  the offset    each weapon was repositioned individually - rifle 0.23 units,
                launcher 1.61, wrench 2.23 - so no single cvar corrects it.
  z-fighting    this script duplicates EVERY triangle in a mesh that has any
                hole, so the already-solid parts end up with coincident faces
                that flicker.

THE MISTAKE WORTH REMEMBERING
-----------------------------
The skeletons matched byte for byte and that was taken as proof that placement
was safe. It is not: the skeleton is only the bone hierarchy. Where the mesh
sits relative to those bones is the weight data, and that was never compared
until the headset said the weapons were sitting up and out.

Check the thing that carries the property you are claiming.
"""
import argparse
import io
import os
import re
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
PK4 = os.path.join(REPO, 'app', 'src', 'main', 'pk4')

WEAPONS = ['autocannon', 'bow', 'crawler', 'hider', 'launcher', 'rifle',
           'soulstripper', 'wrench']

# Single-sided by intent. Mirroring these is a bug, not a fix.
SKIP = ('gui', 'beam', 'glass', 'mask', 'fluid')

# Provenance goes in the md5mesh "commandline" field, not a leading comment.
#
# Model_md5.cpp reads that field and throws it away ("// skip commandline"), so
# it is the slot the format provides for exactly this. A leading // comment
# SHOULD be skipped by idLexer, but the parser runs with LEXFL_ALLOWPATHNAMES,
# which makes '/' a legal name character, and not one of the 99 retail md5mesh
# files starts with a comment - there is no precedent proving it works and no
# reason to find out the hard way in somebody's headset.
PROVENANCE = (
    'generated by tools/release/fill_weapon_backfaces.py from the RETAIL mesh '
    'of the same name; every triangle on an open surface duplicated with '
    'reversed winding so it has a back face; skeleton, vertices and weights '
    'byte-identical to retail; derived from no other author edited model'
)


def retail_index(paks):
    idx = {}
    for name in sorted(os.listdir(paks)):
        if not name.lower().endswith('.pk4') or name.lower() == 'vr_support.pk4':
            continue
        try:
            z = zipfile.ZipFile(os.path.join(paks, name))
        except Exception:
            continue
        for n in z.namelist():
            idx.setdefault(n.lower(), (z, n))
    return idx


def mesh_spans(t):
    out = []
    for m in re.finditer(r'\bmesh\s*\{', t):
        depth = 0
        for k in range(t.index('{', m.start()), len(t)):
            if t[k] == '{':
                depth += 1
            elif t[k] == '}':
                depth -= 1
                if depth == 0:
                    out.append((m.start(), k + 1))
                    break
    return out


def tris_of(blk):
    return [tuple(int(x) for x in g[1:]) for g in
            re.findall(r'tri\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)', blk)]


def open_edges(tris):
    seen = {}
    for a, b, c in tris:
        for e in ((a, b), (b, c), (c, a)):
            k = (min(e), max(e))
            seen[k] = seen.get(k, 0) + 1
    return sum(1 for v in seen.values() if v == 1)


def mirror(blk):
    tris = tris_of(blk)
    if open_edges(tris) == 0:
        return blk, 0
    n = len(tris)
    added = '\n'.join('\ttri %d %d %d %d' % (n + i, c, b, a)
                      for i, (a, b, c) in enumerate(tris))
    blk = re.sub(r'(numtris\s+)(\d+)', lambda m: m.group(1) + str(n * 2), blk, count=1)
    eol = blk.index('\n', blk.rindex('tri '))
    return blk[:eol] + '\n' + added + blk[eol:], n


def skeleton(t):
    m = re.search(r'joints\s*\{(.*?)\n\}', t, re.S)
    return m.group(1) if m else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--paks', required=True, help='a preybase holding retail pak files')
    args = ap.parse_args()

    idx = retail_index(args.paks)
    if not idx:
        sys.exit('no retail paks in %s' % args.paks)

    print('%-14s %-11s %-9s %-13s %s' % ('weapon', 'open edges', 'meshes', 'triangles', 'rig'))
    print('-' * 62)
    bad = 0
    for w in WEAPONS:
        rel = 'models/weapons/%s/%s.md5mesh' % (w, w)
        hit = idx.get(rel)
        if not hit:
            print('%-14s not in the retail paks' % w)
            bad += 1
            continue
        z, member = hit
        src = z.read(member).decode('latin-1')

        out, shift, filled, before_open = src, 0, 0, 0
        for s, e in mesh_spans(src):
            blk = src[s:e]
            name = re.search(r'shader\s+"([^"]+)"', blk)
            nm = (name.group(1) if name else '').lower()
            if any(k in nm for k in SKIP):
                continue
            before_open += open_edges(tris_of(blk))
            new, n = mirror(blk)
            if n:
                filled += 1
            out = out[:s + shift] + new + out[e + shift:]
            shift += len(new) - len(blk)

        if skeleton(src) != skeleton(out):
            print('%-14s SKELETON CHANGED - refusing' % w)
            bad += 1
            continue
        after_open = sum(open_edges(tris_of(out[s:e]))
                         for s, e in mesh_spans(out)
                         if not any(k in (re.search(r'shader\s+"([^"]+)"', out[s:e]).group(1).lower()
                                          if re.search(r'shader\s+"([^"]+)"', out[s:e]) else '')
                                    for k in SKIP))
        tb = sum(int(x) for x in re.findall(r'numtris\s+(\d+)', src))
        ta = sum(int(x) for x in re.findall(r'numtris\s+(\d+)', out))

        dst = os.path.join(PK4, 'models', 'weapons', w, '%s.md5mesh' % w)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        out = re.sub(r'(commandline\s+)"[^"]*"',
                     lambda m: m.group(1) + '"' + PROVENANCE + '"', out, count=1)
        io.open(dst, 'w', encoding='latin-1', newline='\n').write(out)

        print('%-14s %-11s %-9d %-13s %s' % (
            w, '%d -> %d' % (before_open, after_open), filled,
            '%d -> %d' % (tb, ta),
            'identical' if after_open == 0 else 'OPEN EDGES REMAIN'))
        if after_open != 0:
            bad += 1

    print()
    if bad:
        print('%d weapon(s) failed' % bad)
        return 1
    print('all eight closed, every skeleton byte-identical to retail')
    return 0


if __name__ == '__main__':
    sys.exit(main())
