#!/usr/bin/env python3
"""Generate the Windows GL entry-point loader for the PCVR build.

Why this exists
---------------
The engine is written against GLES 2/3 and calls a handful of GL entry points
directly rather than through the engine's own `qgl` function pointers. On
Android those come from libGLESv3.so. On Windows, `opengl32.dll` exports only
GL 1.1 -- everything newer has to be resolved at runtime through
wglGetProcAddress.

Rather than rewrite their call sites, this emits real functions with the exact
GLES prototypes that forward to loaded pointers, so `renderer/framebuffer.cpp`,
`renderer/VertexCache.cpp`, `renderer/draw_gles3_multiview.cpp` and the VR
layer compile and link untouched.

Nothing here is hand-typed: the prototypes are parsed out of the vendored
Khronos headers, and the list of functions to emit is the measured difference
between what those sources call and what `dumpbin /exports opengl32.dll`
actually provides.

Usage:  python tools/gen_gl_loader.py
"""

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GLES = os.path.join(ROOT, 'app', 'src', 'main', 'jni', 'GLES')

# Measured, not guessed. See PROGRESS.md, Milestone 4: every gl* identifier
# referenced by the two module source lists, minus the 337 gl* symbols
# opengl32.dll actually exports, minus the four that VrFramebuffer.c already
# resolves for itself through eglGetProcAddress.
WANT = [
    'glBindBuffer', 'glBindBufferBase', 'glBindFramebuffer', 'glBindRenderbuffer',
    'glBufferData', 'glCheckFramebufferStatus', 'glDeleteBuffers',
    'glDeleteFramebuffers', 'glDeleteRenderbuffers', 'glFramebufferRenderbuffer',
    'glFramebufferTexture2D', 'glGenFramebuffers', 'glGenRenderbuffers',
    'glGetUniformBlockIndex', 'glInvalidateFramebuffer', 'glMapBufferRange',
    'glRenderbufferStorage', 'glTexStorage3D', 'glUniformBlockBinding',
    'glUnmapBuffer',
]

DECL_RE = re.compile(
    r'\s*GL_APICALL\s+(.+?)\s*GL_APIENTRY\s+(gl[A-Za-z0-9_]+)\s*\((.*)\);\s*$')


def parse_headers():
    decls = {}
    for rel in ('GLES2/gl2.h', 'GLES3/gl3.h'):
        path = os.path.join(GLES, rel)
        for line in io.open(path, encoding='utf-8', errors='replace'):
            m = DECL_RE.match(line)
            if m and m.group(2) in WANT and m.group(2) not in decls:
                decls[m.group(2)] = (m.group(1).strip(), m.group(3).strip())
    return decls


def arg_names(args):
    if not args.strip() or args.strip() == 'void':
        return []
    names = []
    for part in args.split(','):
        ids = re.findall(r'[A-Za-z_][A-Za-z0-9_]*', part)
        names.append(ids[-1])
    return names


def main():
    decls = parse_headers()
    missing = [w for w in WANT if w not in decls]
    if missing:
        sys.stderr.write('could not find prototypes for: %s\n' % ', '.join(missing))
        return 1

    nl = chr(10)
    out = []
    a = out.append

    a('// GENERATED by tools/gen_gl_loader.py -- do not edit by hand.')
    a('//')
    a('// Real definitions for the GL entry points this engine calls directly and')
    a('// that opengl32.dll does not export. Prototypes are taken verbatim from the')
    a('// vendored Khronos headers, so these match what the sources were compiled')
    a('// against; each one forwards to a pointer resolved at init.')
    a('//')
    a('// PCVR_GL_Init() must be called once, with a current GL context, before any')
    a('// of these are used. GLimp_Init does that.')
    a('')
    a('#include <windows.h>')
    a('#include <stdio.h>')
    a('#include <GLES2/gl2.h>')
    a('#include <GLES3/gl3.h>')
    a('#include "gl_loader.h"')
    a('')
    a('// wglGetProcAddress only resolves entry points newer than GL 1.1, and')
    a('// returns one of several documented failure values rather than just NULL.')
    a('void *PCVR_GL_GetProc( const char *name ) {')
    a('\tPROC p = wglGetProcAddress( name );')
    a('')
    a('\tif ( p == 0 || p == (PROC)0x1 || p == (PROC)0x2 || p == (PROC)0x3 ||')
    a('\t\t\tp == (PROC)-1 ) {')
    a('\t\tHMODULE m = GetModuleHandleA( "opengl32.dll" );')
    a('\t\tp = m ? GetProcAddress( m, name ) : 0;')
    a('\t}')
    a('')
    a('\treturn (void *)p;')
    a('}')
    a('')

    for w in WANT:
        ret, args = decls[w]
        a('typedef %s (GL_APIENTRY *PFN_PCVR_%s)(%s);' % (ret, w, args))
    a('')
    for w in WANT:
        a('static PFN_PCVR_%s p_%s;' % (w, w))
    a('')

    for w in WANT:
        ret, args = decls[w]
        names = arg_names(args)
        call = 'p_%s( %s )' % (w, ', '.join(names)) if names else 'p_%s()' % w
        a('GL_APICALL %s GL_APIENTRY %s (%s) {' % (ret, w, args))
        if ret.replace(' ', '') == 'void':
            a('\t%s;' % call)
        else:
            a('\treturn %s;' % call)
        a('}')
        a('')

    a('bool PCVR_GL_Init( void ) {')
    a('\t// Idempotent: GLimp_Init can be reached more than once, and the VR layer')
    a('\t// owns the GL context here the way EGL does on Android, so the ordering')
    a('\t// between the two is worth being tolerant about.')
    a('\tstatic bool loaded = false;')
    a('')
    a('\tif ( loaded ) {')
    a('\t\treturn true;')
    a('\t}')
    a('')
    a('\t// If this runs before a context is current, wglGetProcAddress returns')
    a('\t// NULL for everything and the report below names all twenty. That is a')
    a('\t// far better failure than a null call deep inside the renderer.')
    a('\tint missing = 0;')
    a('')
    for w in WANT:
        a('\tp_%s = (PFN_PCVR_%s)PCVR_GL_GetProc( "%s" );' % (w, w, w))
        a('\tif ( !p_%s ) { printf( "PCVR_GL_Init: missing %s' % (w, w) +
          chr(92) + 'n" ); missing++; }')
    a('')
    a('\tif ( missing ) {')
    a('\t\tprintf( "PCVR_GL_Init: %d of ' + str(len(WANT)) +
      ' entry points unresolved' + chr(92) + 'n", missing );')
    a('\t\treturn false;')
    a('\t}')
    a('')
    a('\tloaded = true;')
    a('\treturn true;')
    a('}')
    a('')

    src = nl.join(out)
    dst = os.path.join(GLES, 'gl_loader.cpp')
    io.open(dst, 'w', encoding='utf-8', newline=nl).write(src)

    hdr = nl.join([
        '// GENERATED by tools/gen_gl_loader.py -- do not edit by hand.',
        '#ifndef PCVR_GL_LOADER_H',
        '#define PCVR_GL_LOADER_H',
        '',
        '// The VR layer is C and calls both of these; this file is compiled as C++.',
        '// Same wrapper their own VrCommon.h uses. (The gl* entry points below do',
        '// not need it: the Khronos headers already declare them extern "C".)',
        '#ifdef __cplusplus',
        'extern "C" {',
        '#endif',
        '',
        '// Resolves the GL entry points opengl32.dll does not export. Call once,',
        '// with a current GL context, before any rendering. Returns false and names',
        '// the offenders on stdout if anything is unresolved.',
        'bool PCVR_GL_Init( void );',
        '',
        '// Resolves any GL entry point by name: wglGetProcAddress, falling back to',
        '// opengl32.dll for the GL 1.1 set it refuses. This is what',
        '// GLimp_ExtensionPointer uses on Windows to fill the engine qgl pointers.',
        'void *PCVR_GL_GetProc( const char *name );',
        '',
        '',
        '#ifdef __cplusplus',
        '}',
        '#endif',
        '',
        '#endif',
        '',
    ])
    io.open(os.path.join(GLES, 'gl_loader.h'), 'w', encoding='utf-8', newline=nl).write(hdr)

    print('wrote %s (%d entry points)' % (dst, len(WANT)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
