#!/usr/bin/env python3
"""Generate cmake/sources.cmake from their Android makefiles.

The authority for what belongs in each module is
neo/mobile/Android.mk (the engine, libdoom3) and neo/mobile/Android_game.mk
(the game, libgame). Transcribing ~500 filenames by hand would be a good way to
introduce a silent difference, so they are parsed instead, and their
commented-out lines are honoured -- ai_Navigator.cpp, for one, is `#`-ed out of
their build.

Only the platform layer is substituted:

  removed   sys/posix/*, sys/linux/main.cpp     POSIX entry point and syscalls
  added     sys/win32/win_main.cpp, win_net.cpp, win_shared.cpp,
            win_syscon.cpp, win_pcvr.cpp        the Win32 equivalents
  added     ../GLES/gl_loader.cpp               generated GL entry points

Everything else -- renderer, framework, cm, sound, ui, idlib, the aas/dmap/roq
compilers, the VR layer, and mobile/game_interface.cpp, which despite its name
has no Android code in it at all -- is taken exactly as their makefiles list it.

Usage:  python tools/gen_cmake_sources.py
"""

import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
JNI = os.path.join(ROOT, 'app', 'src', 'main', 'jni')
NEO = os.path.join(JNI, 'd3es-multithread-master', 'neo')

BS = chr(92)

DROP_PREFIXES = ('sys/posix/', 'sys/linux/')

# idlib/bv/Frustum.cpp guards its ProjectionBounds(const idBox&) with
# `#ifndef __linux__`, and Frustum_gcc.cpp supplies the Linux replacement. Their
# Android.mk lists both because __linux__ is defined there; on Windows both
# compile and the linker sees the symbol twice. Dropping the _gcc variant leaves
# the original id implementation, which is the one a non-Linux build is meant to
# use.
DROP_FILES = ('idlib/bv/Frustum_gcc.cpp',)

ENGINE_EXTRA = [
    'sys/win32/win_main.cpp',
    # win_input.cpp is DirectInput and this fork takes input through SDL in
    # sys/events.cpp, so none of its input path runs. It is here for one
    # function: Win_MapKey, which win_syscon.cpp calls to translate scancodes
    # for the early-console window. Taking their implementation beats writing
    # a scancode table from scratch.
    'sys/win32/win_input.cpp',
    'sys/win32/win_net.cpp',
    'sys/win32/win_shared.cpp',
    'sys/win32/win_syscon.cpp',
    'sys/win32/win_pcvr.cpp',
]


def parse(mk):
    """Pull source paths out of an Android.mk, skipping commented-out lines."""
    out = []
    for line in io.open(mk, encoding='utf-8', errors='replace').read().split(chr(10)):
        s = line.strip()
        if s.startswith('#'):
            continue
        s = s.rstrip(BS).strip()
        if not (s.endswith('.cpp') or s.endswith('.c')):
            continue
        # A few entries are written as an assignment on one line, e.g.
        #   SRC_ANDROID = mobile/game_interface.cpp
        # Taking only the right-hand side catches those; skipping any line with
        # an '=' silently dropped game_interface.cpp, which the VR layer calls
        # into (Android_GetCVarInteger and the impulse/command bridge).
        if '=' in s:
            s = s.split('=', 1)[1].strip()
        if ' ' in s or '$' in s:
            continue
        out.append(s)
    return out


def resolve(rel):
    """Their makefiles are relative to neo/; emit paths relative to the repo root
    so the generated file is portable rather than tied to one checkout."""
    absolute = os.path.normpath(os.path.join(NEO, rel))
    return os.path.relpath(absolute, ROOT).replace(BS, '/')


def main():
    engine = parse(os.path.join(NEO, 'mobile', 'Android.mk'))
    game = parse(os.path.join(NEO, 'mobile', 'Android_game.mk'))
    game = [f for f in game if f not in DROP_FILES]

    def is_dropped(f):
        return f.startswith(DROP_PREFIXES) or f in DROP_FILES

    dropped = [f for f in engine if is_dropped(f)]
    engine = [f for f in engine if not is_dropped(f)]
    engine += ENGINE_EXTRA
    engine.append(os.path.relpath(
        os.path.join(JNI, 'GLES', 'gl_loader.cpp'), NEO).replace(BS, '/'))

    missing = [f for f in engine + game if not os.path.exists(resolve(f))]
    if missing:
        for m in missing:
            sys.stderr.write('missing on disk: %s\n' % m)
        return 1

    nl = chr(10)
    lines = [
        '# GENERATED by tools/gen_cmake_sources.py -- do not edit by hand.',
        '#',
        '# Parsed from neo/mobile/Android.mk and neo/mobile/Android_game.mk, which',
        '# are the authority for what each module contains. Only the platform layer',
        '# is substituted; see the generator for the exact list.',
        '#',
        '# Paths are relative to PREYVR_ROOT, which CMakeLists.txt sets.',
        '',
        '# Dropped from the engine module (POSIX platform layer):',
    ]
    for d in sorted(dropped):
        lines.append('#   ' + d)
    lines += ['', 'set(PREYVR_ENGINE_SOURCES']
    for f in engine:
        lines.append('    ${PREYVR_ROOT}/' + resolve(f))
    lines += [')', '', 'set(PREYVR_GAME_SOURCES']
    for f in game:
        lines.append('    ${PREYVR_ROOT}/' + resolve(f))
    lines += [')', '']

    dst = os.path.join(ROOT, 'cmake', 'sources.cmake')
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    io.open(dst, 'w', encoding='utf-8', newline=nl).write(nl.join(lines))

    print('wrote %s' % dst)
    print('  engine module : %d sources (%d POSIX files dropped, %d Win32 added)'
          % (len(engine), len(dropped), len(ENGINE_EXTRA) + 1))
    print('  game module   : %d sources' % len(game))
    return 0


if __name__ == '__main__':
    sys.exit(main())
